version: '3.9'

services:
  postgres:
    container_name: chaty_db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: chaty
